#!/usr/bin/perl

use strict;
use warnings;
use lib 'lib';

#sub POE::Kernel::TRACE_SIGNALS () { 1 }
#sub POE::Kernel::TRACE_EVENTS () { 1 }
#sub POE::Kernel::TRACE_REFCNT () { 1 }
#sub POE::Kernel::TRACE_SESSIONS () { 1 }
use POE::Kernel {loop => "Glib"};
use POE::Session;
use POE;

use Tether;

Tether->new();
POE::Kernel->run();
